Dz 1
vederko-p/RecService pull request #2
Opened 2022-11-27 21:45 UTC by vederko-p

2022-11-28 14:08 UTC, groundmax requested changes

2022-11-28 14:08 UTC, groundmax commented on tests/api/test_views.py
> +var_expect = [
Отличное использование mark.parametrize, молодцы!

2022-11-28 14:08 UTC, groundmax commented on tests/api/test_views.py
> +    print(f'var: {var}')
А вот использовать принты плохая практика, либо убирайте вообще, либо пользуйтесь логгером. 
В данном случае, если что-то пойдет не так с тестами, то вам всю нужную информацию подсветит pytest, поэтому можно вообще убрать.

2022-11-28 14:08 UTC, groundmax commented on tests/api/test_views.py
> +    expectation: HTTPStatus
Где-то запятые ставите, а где-то нет, лучше соблюдать один подход. Чтобы об этом не париться, еще раз напомню вам про black :)

2022-11-28 14:08 UTC, groundmax commented on service/api/views.py
> +from service.api.exceptions import UserNotFoundError, ModelNotFoundError
Я так понимаю, вы не пользовались make format? Потому что здесь бы isort исправил очередность импортов)

2022-11-28 14:08 UTC, groundmax commented on tests/api/test_views.py
> +BAD_TOKEN = os.getenv('BAD_API_TOKEN')
Bad_token можно здесь написать, тк это же нереальный/неправильный токен, то есть брат из переменных окружения неправильный токен это оверкилл

2022-11-28 15:27 UTC, vederko-p commented on service/api/secure_token.py
> +    verifyed = check_token(token)
совершенно точно `verified`

2022-11-28 15:30 UTC, vederko-p commented on service/api/views.py
> +    if models_base.check_model(bot_request.model_name):
Почему лучше?

2022-11-28 15:33 UTC, vederko-p commented on service/api/views.py
> +from service.api.exceptions import UserNotFoundError, ModelNotFoundError
действительно, не пользовались

2022-11-28 15:34 UTC, vederko-p commented on tests/api/test_views.py
> +BAD_TOKEN = os.getenv('BAD_API_TOKEN')
ахах, да, согласен
ну мало ли мне очень нравится мой badtoken и я никому не хочу его показывать
однако с другой стороны тогда токены будут храниться в разных местах, пусть даже неправильные

2022-12-06 13:24 UTC, vederko-p commented on service/api/models/base_model.py
> +
Исправлено

2022-12-06 13:24 UTC, vederko-p commented on service/api/secure_token.py
> +    verifyed = check_token(token)
Исправлено

2022-12-06 13:24 UTC, vederko-p commented on service/api/secure_token.py
> +async def get_k_itmes(request: Request) -> int:
Исправлено

2022-12-06 13:24 UTC, vederko-p commented on service/api/models/base_model.py
> +class BaseModel:
Исправлено

2022-12-06 13:25 UTC, vederko-p commented on service/api/models/base_model.py
> +    def predict(self):
Исправлено

2022-12-06 13:25 UTC, vederko-p commented on service/api/views.py
> +resonses = {
Исправлено

2022-12-06 13:25 UTC, vederko-p commented on tests/api/test_views.py
> +GOOD_TOKEN = os.getenv('GOOD_API_TOKEN')
Он упадет с ошибкой `KeyError`, которую все равно придется обрабатывать, чтобы вывести ее как отсутсвие переменной окружения.

2022-12-06 13:26 UTC, vederko-p commented on tests/api/test_views.py
> +    print(f'var: {var}')
Исправлено

2022-12-06 13:26 UTC, vederko-p commented on tests/api/test_views.py
> +    expectation: HTTPStatus
Исправлено

2022-12-06 19:36 UTC, groundmax commented on pyproject.toml
> +python-multipart = "^0.0.5"
Вы же уже это делаете в тестах))) Подгружаете переменные окружения через os.getenv

2022-12-06 19:44 UTC, groundmax commented on service/api/views.py
> +    if models_base.check_model(bot_request.model_name):
Вот тут хорошо написано - https://stackoverflow.com/questions/12265451/ask-forgiveness-not-permission-explain

К нашему это не особо относится, пускай останется так, как есть

2022-12-06 19:53 UTC, vederko-p commented on service/api/models/test_model.py
> +from typing import List as _List
Исправлено

2022-12-06 19:54 UTC, groundmax commented on service/api/models/base_model.py
> +
Кажется, что CI как не работал, так и не работает)
Если бы он работал, тогда было бы видно в ui "All checks have passed":
![image](https://user-images.githubusercontent.com/36198818/206009246-9d3ab0cd-fe37-47b4-8ba0-957e7e61e83a.png)

2022-12-07 21:52 UTC, groundmax commented on service/api/models/base_model.py
> +
![image](https://user-images.githubusercontent.com/36198818/206304395-18bea0a7-0179-47b3-af9f-253b575f2459.png)
CI упал с ошибкой

2022-12-07 21:53 UTC, groundmax approved these changes
Оставляю фикс CI на вас, с остальным пойдет, баллы смотрите в таблице
![image](https://user-images.githubusercontent.com/36198818/206305341-aa49ee99-0f57-4a30-ab6d-5fab0471d14c.png)

2022-12-08 22:18 UTC, merged