Dz 3 after merge DZ_2 -> DZ_3
vederko-p/RecService pull request #5
Opened 2022-12-08 22:47 UTC by vederko-p

2022-12-09 22:04 UTC, groundmax requested changes
В целом все очень круто, большинство комментариев в основном про уточнения, нежели про изменения. Критического-критического ничего нет, только прошу вас разкомментировать проверку линтеров в ci.

2022-12-09 22:04 UTC, groundmax commented on userknn.py
> +    def get_mappings(self, train):
Так как этот код не используется в сервисе, также как и в ноутбучке, я особо не докапывался для аннотаций. Но напомню лишний раз, что если захотели писать их, то пишите везде, придерживайтесь единообразия, в будущем поможет заранее устранить множество вопросов)

2022-12-11 15:59 UTC, groundmax commented
Ребят, еще просьба, приложите, пожалуйста, скрин ответов вашего сервиса для пользователей: 425823, 964868, 327683, 524297

2022-12-11 17:32 UTC, vederko-p commented
Ответ одинаковый для всех

![image](https://user-images.githubusercontent.com/47597634/206919201-1f7d3bf0-7f78-4503-8496-6e01b0450f16.png)

2022-12-14 02:41 UTC, merged